# Generated by Django 4.2.4 on 2023-08-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_consultation_courier_florist_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Курьер', 'verbose_name_plural': 'Курьеры'},
        ),
        migrations.AlterModelOptions(
            name='florist',
            options={'verbose_name': 'Флорист', 'verbose_name_plural': 'Флористы'},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
    ]
